[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
# cargo のバイナリが存在するディレクトリを検索できる（通常はセキュリティ上の都合で Current dir は除外される）
assert_cmd = "1"